{
 "title": "MQ Metrics Dashboard",
 "description": "This dashboard displays metrics collected by mq-metrics-pyclient",
 "tags": [ "mq-metrics-pyclient" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "qmname",
    "label": "Queue Manager",
    "query": "label_values(mq_manager_status, qmname)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mq_manager_status{ qmname=~\"$qmname\"},instance)"
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": "label_values(mq_channel_status{qmname=~\"$qmname\", instance=~\"$instance\"}, channel)"
   }
  ]
 },
 "panels": [
  {
   "title": "MQ Managers, Listeners and Channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "MQ Manager Status",
   "type": "table",
   "description": "The panel shows the mq_manager_status metric.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mq_manager_status{qmname=~\"$qmname\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "MQ Listeners Status",
   "type": "table",
   "description": "The panel shows the mq_listener_status metric",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mq_listener_status{qmname=~\"$qmname\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "MQ Channels Status",
   "type": "table",
   "description": "The panel shows the mq_channel_status metric",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "mq_channel_status{qmname=~\"$qmname\", instance=~\"$instance\", channel=~\"$channel\"}"
    }
   ]
  },
  { "title": "Application queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Application queues utilization",
   "type": "graph",
   "description": "The panel shows the utilization of application queues.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mq_queue_curdepth{qmname=~\"$qmname\", instance=~\"$instance\", queuename !~\"SYSTEM.(.*)|AMQ.MQEXPLORER.(.*)\"}/mq_queue_maxdepth{qmname=~\"$qmname\", instance=~\"$instance\", queuename !~\"SYSTEM.(.*)|AMQ.MQEXPLORER.(.*)\"}*100",
     "legendFormat": "{{qmname}} {{instance}} {{queuename}}"
    }
   ]
  },
  {
   "title": "Application queues current depth",
   "type": "graph",
   "description": "The panel shows the mq_queue_curdepth metric",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mq_queue_curdepth{qmname=~\"$qmname\", instance=~\"$instance\", queuename !~\"SYSTEM.(.*)|AMQ.MQEXPLORER.(.*)\"}",
     "legendFormat": "{{qmname}} {{instance}} {{queuename}}"
    }
   ]
  },
  { "title": "System queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "System queues utilization",
   "type": "graph",
   "description": "The panel shows the utilization of system queues.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mq_queue_curdepth{qmname=~\"$qmname\", instance=~\"$instance\", queuename =~\"SYSTEM.(.*)|AMQ.MQEXPLORER.(.*)\"}/mq_queue_maxdepth{qmname=~\"$qmname\", instance=~\"$instance\", queuename =~\"SYSTEM.(.*)|AMQ.MQEXPLORER.(.*)\"}*100",
     "legendFormat": "{{qmname}} {{instance}} {{queuename}}"
    }
   ]
  },
  {
   "title": "System queues current depth",
   "type": "graph",
   "description": "The panel shows the mq_queue_curdepth metric",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mq_queue_curdepth{qmname=~\"$qmname\", instance=~\"$instance\", queuename =~\"SYSTEM.(.*)|AMQ.MQEXPLORER.(.*)\"}",
     "legendFormat": "{{qmname}} {{instance}} {{queuename}}"
    }
   ]
  }
 ]
}